using DalApi;
using System.Buffers.Text;
using System.Net.Mail;
using System.Security;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Helpers;

internal static class CourierManager
{
    private static IDal s_dal = Factory.Get; //stage 4

    private static DO.Courier BOToDOCourier(BO.Courier boCourier)
    {
        DO.Courier doCourier = new DO.Courier()
        {
            Id = boCourier.Id,
            FullName = boCourier.FullName,
            Email = boCourier.Email,
            PhoneNumber = boCourier.PhoneNumber,
            Active = boCourier.IsActive,
            DistanceToDelivery = boCourier.DistanceToDelivery,
            DeliveryType = (DO.Enums.ShippingType)boCourier.DeliveryType!,
            EmploymentStartDate = boCourier.EmploymentStartDate
        };
        return doCourier;
    }

    internal static void CheckCorrectnessVariables(BO.Courier boCourier)
    {
        // Execute all individual property validations
        CheckId(boCourier.Id);
        CheckEmail(boCourier.Email);
        CheckPhoneNumber(boCourier.PhoneNumber);
        CheckPassword(boCourier.Password);
        CheckPersonalMaxDistance(boCourier.DistanceToDelivery);
    }
    internal static void AddCourier(int requesterId, BO.Courier boCourier)
    {
        DO.Courier doCourier = BOToDOCourier(boCourier);
        try
        {
            s_dal.Courier.Create(doCourier);
        }
        catch (DO.DalAlreadyExistsException ex)
        {
            throw new BO.BlAlreadyExistsException($"Courier with ID {doCourier.Id} already exists", ex);
        }
    }

    internal static void AccessPermissionToManager(int requesterId)
    {
        if (requesterId != DalApi.Factory.Get.Config.ManagerId)
            throw new BO.BLAccessPermission("ERROR: No access permission");
    }

    #region Check New Courier Fildes
    internal static void CheckId(int id)   // Generated by Gemini based on the prompt: "Create a function to check a control digit"

    {
        // Basic range check
        if (id < 0)
            throw new BO.BLInvalidDataException("ERROR: Invalid ID number");

        // Pad to 9 digits for algorithm consistency
        string idString = id.ToString().PadLeft(9, '0');
        int sum = 0;

        // Calculate control digit sum (Israeli ID algorithm)
        for (int i = 0; i < 9; i++)
        {
            int digit = idString[i] - '0';
            int weight = (i % 2 == 0) ? 1 : 2;
            int step = digit * weight;

            if (step > 9)
                step -= 9;

            sum += step;
        }

        // Validate modulo 10
        if (sum % 10 != 0)
            throw new BO.BLInvalidDataException("ERROR: Invalid ID number (Checksum failed)");
    }

    internal static void CheckPhoneNumber(string phoneNumber)
    {
        // Validate format: 10 digits, starts with '05', contains only numbers
        if (string.IsNullOrWhiteSpace(phoneNumber) ||
            phoneNumber.Length != 10 ||
            phoneNumber[0] != '0' ||
            phoneNumber[1] != '5' ||
            !phoneNumber.All(char.IsDigit))
        {
            throw new BO.BLInvalidDataException("ERROR: Invalid phone number. Must start with '05' and contain 10 digits.");
        }
    }

    internal static void CheckEmail(string email)
    {
        // Ensure email is provided
        if (string.IsNullOrWhiteSpace(email))
        {
            throw new BO.BLInvalidDataException("ERROR: Email address cannot be empty");
        }

        // Validate format using MailAddress parser
        try
        {
            var addr = new MailAddress(email);
            if (addr.Address != email)
                throw new BO.BLInvalidDataException("ERROR: Invalid email address format");
        }
        catch
        {
            throw new BO.BLInvalidDataException("ERROR: Invalid email address format");
        }
    }

    internal static void CheckPassword(string password)
    {
        // Enforce length policy
        if (string.IsNullOrEmpty(password) || password.Length < 8)
            throw new BO.BLInvalidDataException("ERROR: Invalid password, must contain at least 8 characters.");

        // Enforce complexity policy (Upper, Lower, Digit)
        if (!password.Any(char.IsUpper) || !password.Any(char.IsLower) || !password.Any(char.IsDigit))
            throw new BO.BLInvalidDataException("ERROR: Invalid password, must contain uppercase, lowercase, and a number.");
    }

    internal static void CheckPersonalMaxDistance(double? maxDistance)
    {
        // Null is a valid value (indicates no limit)
        if (maxDistance != null)
        {
            // Retrieve global limit from DAL
            double companyMaxLimit = DalApi.Factory.Get.Config.MaxAirDistance ?? 0;

            // Validate positive value
            if (maxDistance <= 0)
                throw new BO.BLInvalidDataException("ERROR: Max distance must be positive.");

            // Validate against global company limit
            if (companyMaxLimit > 0 && maxDistance > companyMaxLimit)
                throw new BO.BLInvalidDataException($"ERROR: Personal max distance ({maxDistance}) cannot exceed company limit ({companyMaxLimit}).");
        }
    }
}

    #endregion Check New Courier Fildes