using DalApi;
using System.Buffers.Text;
using System.Net.Mail;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Helpers;

internal static class CourierManager
{
    private static IDal s_dal = Factory.Get; //stage 4

    private static DO.Courier BOToDOCourier(BO.Courier boCourier)
    {
        DO.Courier doCourier = new DO.Courier()
        {
            Id = boCourier.Id,
            FullName = boCourier.FullName,
            Email = boCourier.Email,
            PhoneNumber = boCourier.PhoneNumber,
            Active = boCourier.IsActive,
            DistanceToDelivery = boCourier.DistanceToDelivery,
            DeliveryType = (DO.Enums.ShippingType)boCourier.DeliveryType!,
            EmploymentStartDate = boCourier.EmploymentStartDate
        };
        return doCourier;
    }

    internal static void cheackCorrectnessVariables(BO.Courier boCourier)
    {

    }
    internal static void AddCourier(int id, BO.Courier courier)
    {

    }

    // Generated by Gemini based on the prompt: "Create a function to check a control digit"
    internal static void cheackId(int id)
    {
        if (id < 0)
            throw new BO.BLInvalidDataException($"ERROR : Invalid ID number");
        // else

        // Convert to string and pad with zeros to ensure 9 digits
        string idString = id.ToString().PadLeft(9, '0');

        int sum = 0;

        for (int i = 0; i < 9; i++)
        {
            // Parse char to int
            int digit = idString[i] - '0';

            // Calculate weight: 1 for even index (0,2...), 2 for odd index (1,3...)
            int weight = (i % 2 == 0) ? 1 : 2;

            int step = digit * weight;

            // If result is double digit, sum its digits (e.g., 12 -> 1+2=3)
            // Math trick: for numbers 10-18, subtracting 9 gives the sum of digits
            if (step > 9)
                step -= 9;

            sum += step;
        }
        // Valid if total sum is divisible by 10
        if (sum % 10 != 0)
            throw new BO.BLInvalidDataException($"ERROR : Invalid ID number");
    }

    internal static void cheackPhoneNumber(string phoneNumber)
    {
        if (phoneNumber.Length != 10 || phoneNumber[0] != 0 || phoneNumber[1] != 5)
            throw new BO.BLInvalidDataException($"ERROR : Invalid phone number");
    }

    internal static void cheackEmail(string email)
    {

        if (!string.IsNullOrWhiteSpace(email))
        {
            throw new BO.BLInvalidDataException($"ERROR : Invalid mail Address");
        }
        var addr = new MailAddress(email);

        if (addr.Address != email)
            throw new BO.BLInvalidDataException($"ERROR : Invalid mail Address");
    }

}
